networks:
  app_network:
    driver: bridge

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    networks:
      - app_network
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123
    networks:
      - app_network
    depends_on:
      - postgresdb
